version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: myapp-postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - myapp-postgres-data:/var/lib/postgresql/data

volumes:
  myapp-postgres-data: